namespace MudClient.Core.Equipment;

/// <summary>Body location of a random item generated by the game server.</summary>
public enum RandomItemCategory
{
    Weapon, Torso, Head, Face, Hands, Feet, Shield, Finger, Neck, Gem, Food, Shoulders, Ear, Legs, Arms, Wrist
}

/// <summary>A server command that operates on a confirmed group of items in one source list.</summary>
public sealed record ItemBulkGroup(string DisplayName, string CommandArgument, IReadOnlyList<string> ItemNames)
{
    public int Count => ItemNames.Count;
}

/// <summary>Unique noun signatures for random items, grouped by their server generator and wear
/// location. They were extracted from <c>random_items.c</c> and normalized to the ASCII spelling
/// used in client logs. Adjectives, materials and other random name modifiers are deliberately
/// excluded.</summary>
public static class RandomItemNameCatalog
{
    private static readonly IReadOnlyDictionary<RandomItemCategory, IReadOnlyList<string>> Catalog =
        new Dictionary<RandomItemCategory, IReadOnlyList<string>>
        {
            [RandomItemCategory.Weapon] = [
                "bat", "bastelard", "berdysz", "berlo", "bicz", "bulawa", "buzdygan", "cep",
                "cinquedea", "gizarma", "glewia", "halabarda", "harpun",
                "kanczug", "kij", "kiscien", "korbacz", "kosa", "kostur", "laga", "labrys",
                "laska", "maczuga", "miecz", "mizerykordia", "mlot", "morgensztern", "nadziak",
                "naginata", "nahaj", "noz", "obuch", "oszczep", "pala", "partyzana", "pika",
                "puginal", "rohatyna", "siekiera", "siekierka", "sztylet", "tasak", "topor",
                "trojzab", "tulich", "wakizashi", "wekiera", "widly", "wlocznia"
            ],
            [RandomItemCategory.Torso] = ["zbroja", "kolczuga"],
            [RandomItemCategory.Head] = ["helm"],
            [RandomItemCategory.Face] = ["maska"],
            [RandomItemCategory.Hands] = ["rekawice"],
            [RandomItemCategory.Feet] = ["buty", "drewniaki"],
            [RandomItemCategory.Shield] = ["pawez", "puklerz", "tarcza"],
            [RandomItemCategory.Finger] = ["pierscien", "obraczka"],
            [RandomItemCategory.Neck] = [
                "amulet", "fascinum", "fetysz", "kamien", "medalion", "naszyjnik", "oko", "symbol",
                "talizman", "wisior", "wisiorek"
            ],
            [RandomItemCategory.Gem] = [
                "agat", "agronit", "akwamaryn", "aleksandryt", "ametyst", "andaryt", "azradunin",
                "azuryt", "bursztyn", "chalcedon", "chryzoberyl", "chryzopaz", "cyrkon", "cytryn",
                "deggialryt", "diament", "dipsoid", "drakolid", "feerialyd", "furgasyd", "gagat",
                "garloopel", "granat", "gurthgyr", "gwiazda", "hematyt", "hiacynt", "jadeit", "jaspis",
                "kaintid", "kamien", "karnelian", "koral", "kordun", "krysztal", "kwarc", "krwawnik",
                "lazuryt", "lza", "malachit", "maronid", "nefryt", "obsydian", "oczko", "oliwin", "onyks",
                "opal", "perla", "pirop", "razoryl", "rodochrozyt", "rubin", "sardonyks", "sfin", "shandon",
                "spinel", "szafir", "szmaragd", "tanonir", "tchzar", "topaz", "turkus", "turmalin"
            ],
            [RandomItemCategory.Food] = ["jablko", "jagoda", "suchar"],
            [RandomItemCategory.Shoulders] = [
                "calun", "habit", "kapa", "kapota", "oponcza", "peleryna", "pelerynka", "plaszcz", "szal", "szata"
            ],
            [RandomItemCategory.Ear] = ["klips", "kolczyk", "lzy", "slepia"],
            [RandomItemCategory.Legs] = ["nabioderniki", "nagolenniki", "nakolanniki", "spodnie"],
            [RandomItemCategory.Arms] = ["naramienniki", "nareczaki", "narekawniki", "rekawy"],
            [RandomItemCategory.Wrist] = ["bransoleta", "bransoletka", "skora"]
        };

    public static IReadOnlyDictionary<RandomItemCategory, IReadOnlyList<string>> NamesByCategory => Catalog;

    public static IReadOnlyList<string> GetNames(RandomItemCategory category) =>
        Catalog.TryGetValue(category, out var names) ? names : [];

    /// <summary>Builds only bulk actions supported by an observed wildcard convention. Ordinary
    /// groups use the exact noun from the item name (for example <c>all.kolczyk</c>), gemstones
    /// use the server's collective <c>all.klejnot</c>, and ear/finger/wrist jewellery additionally
    /// offers the server's collective <c>all.gem</c>. Repeated nouns outside the catalog are
    /// retained exactly as observed instead of being assigned an invented category.</summary>
    public static IReadOnlyList<ItemBulkGroup> GetBulkGroups(IEnumerable<string> itemNames, string? selectedItemName = null)
    {
        var sourceItems = itemNames
            .Where(name => !string.IsNullOrWhiteSpace(name))
            .Select(name => new ClassifiedItem(name, GetPrimarySignature(name)))
            .ToArray();
        if (sourceItems.Length < 2) return [];

        var items = sourceItems.Where(item => item.Signature is not null).ToArray();

        var hasSelectedItem = !string.IsNullOrWhiteSpace(selectedItemName);
        var selected = !hasSelectedItem
            ? null
            : GetPrimarySignature(selectedItemName!);
        bool IncludesSelected(Func<ItemSignature, bool> predicate) => !hasSelectedItem || (selected is not null && predicate(selected));
        var groups = new List<ItemBulkGroup>();

        var gems = items.Where(item => item.Signature!.Category == RandomItemCategory.Gem).Select(item => item.Name).ToArray();
        if (gems.Length > 1 && IncludesSelected(signature => signature.Category == RandomItemCategory.Gem))
        {
            groups.Add(new ItemBulkGroup($"Wszystkie klejnoty ({gems.Length})", "all.klejnot", gems));
        }

        var jewellery = items.Where(item => IsJewellery(item.Signature!.Category)).Select(item => item.Name).ToArray();
        if (jewellery.Length > 1 && IncludesSelected(signature => IsJewellery(signature.Category)))
        {
            groups.Add(new ItemBulkGroup($"Cała biżuteria ({jewellery.Length})", "all.gem", jewellery));
        }

        foreach (var group in items
            .Where(item => item.Signature!.Category != RandomItemCategory.Gem)
            .GroupBy(item => item.Signature!, ItemSignatureComparer.Instance)
            .Where(group => group.Count() > 1)
            .Where(group => IncludesSelected(signature => ItemSignatureComparer.Instance.Equals(signature, group.Key)))
            .OrderBy(group => group.Key.Noun, StringComparer.CurrentCultureIgnoreCase))
        {
            var names = group.Select(item => item.Name).ToArray();
            groups.Add(new ItemBulkGroup($"Wszystkie typu „{group.Key.Noun}” ({names.Length})", $"all.{group.Key.Noun}", names));
        }

        // The catalog deliberately contains only generated equipment nouns. A repeated noun
        // outside it (observed examples: "tatuaz" and "kamien mocy") is still a useful, exact
        // server wildcard target. Keep it separate from catalog groups to avoid guessing a slot.
        var genericItems = sourceItems
            .Where(item => item.Signature is null)
            .Select(item => new GenericItem(item.Name, GetGenericBatchNoun(item.Name)))
            .Where(item => item.Noun is not null)
            .ToArray();
        var selectedGenericNoun = selected is null && hasSelectedItem ? GetGenericBatchNoun(selectedItemName!) : null;
        foreach (var group in genericItems
            .GroupBy(item => item.Noun!, StringComparer.OrdinalIgnoreCase)
            .Where(group => group.Count() > 1)
            .Where(group => !hasSelectedItem || string.Equals(group.Key, selectedGenericNoun, StringComparison.OrdinalIgnoreCase))
            .OrderBy(group => group.Key, StringComparer.CurrentCultureIgnoreCase))
        {
            var names = group.Select(item => item.Name).ToArray();
            groups.Add(new ItemBulkGroup($"Wszystkie typu „{group.Key}” ({names.Length})", $"all.{group.Key}", names));
        }

        return groups;
    }

    /// <summary>Returns a Polish slot label only when the displayed name has exactly one catalog
    /// category. A word such as "kamien" occurs in more than one source category, so it remains
    /// intentionally unlabeled rather than being guessed.</summary>
    public static string GetPolishSlotLabel(string itemName)
    {
        var words = EquipmentInventorySnapshotParser.GetPlainItemName(itemName)
            .Split(' ', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
            .ToHashSet(StringComparer.OrdinalIgnoreCase);
        var matches = Catalog
            .Where(entry => entry.Value.Any(words.Contains))
            .Select(entry => entry.Key)
            .ToArray();

        return matches.Length == 1 ? PolishSlotLabels.GetValueOrDefault(matches[0], string.Empty) : string.Empty;
    }

    private static readonly IReadOnlyDictionary<RandomItemCategory, string> PolishSlotLabels =
        new Dictionary<RandomItemCategory, string>
        {
            [RandomItemCategory.Weapon] = "broń",
            [RandomItemCategory.Torso] = "tułów",
            [RandomItemCategory.Head] = "głowa",
            [RandomItemCategory.Face] = "twarz",
            [RandomItemCategory.Hands] = "ręce",
            [RandomItemCategory.Feet] = "stopy",
            [RandomItemCategory.Shield] = "tarcza",
            [RandomItemCategory.Finger] = "palec",
            [RandomItemCategory.Neck] = "szyja",
            [RandomItemCategory.Gem] = "gem",
            [RandomItemCategory.Food] = "jedzenie",
            [RandomItemCategory.Shoulders] = "ramiona",
            [RandomItemCategory.Ear] = "ucho",
            [RandomItemCategory.Legs] = "nogi",
            [RandomItemCategory.Arms] = "ramiona",
            [RandomItemCategory.Wrist] = "nadgarstek"
        };

    private static ItemSignature? GetPrimarySignature(string itemName)
    {
        foreach (var word in EquipmentInventorySnapshotParser.GetPlainItemName(itemName)
            .Split(' ', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
        {
            var matches = Catalog
                .Where(entry => entry.Value.Contains(word, StringComparer.OrdinalIgnoreCase))
                .Select(entry => entry.Key)
                .ToArray();
            if (matches.Length == 1) return new ItemSignature(matches[0], word.ToLowerInvariant());
        }

        return null;
    }

    private static bool IsJewellery(RandomItemCategory category) =>
        category is RandomItemCategory.Ear or RandomItemCategory.Finger or RandomItemCategory.Wrist;

    private static string? GetGenericBatchNoun(string itemName) => EquipmentInventorySnapshotParser.GetItemCommandWords(itemName)
        .FirstOrDefault(word => !GenericDescriptorWords.Contains(word));

    // Only modifiers repeatedly seen in names are excluded. The remaining first meaningful word
    // is retained verbatim, so the client never invents a server wildcard noun.
    private static readonly HashSet<string> GenericDescriptorWords = new(StringComparer.OrdinalIgnoreCase)
    {
        "bardzo", "cala", "ciekawy", "cienki", "czarny", "dlugi", "doskonaly", "duzy",
        "dwu", "dwureczny", "elfi", "fikusny", "gigantyczny", "gruby", "krotki", "maly",
        "magiczna", "magiczny", "miedziany", "mithrilowy", "nieduzy", "niepozorny", "opalizujacy", "pieknie",
        "piekny", "plaski", "popekana", "prosta", "sredni", "srebrna", "stalowy", "szkarlatna",
        "spory", "tajemniczy", "wielki", "wykonany", "zabkowany", "zagadkowy", "zdobione", "zelazny", "zloty"
    };

    private sealed record ClassifiedItem(string Name, ItemSignature? Signature);
    private sealed record GenericItem(string Name, string? Noun);
    private sealed record ItemSignature(RandomItemCategory Category, string Noun);
    private sealed class ItemSignatureComparer : IEqualityComparer<ItemSignature>
    {
        public static readonly ItemSignatureComparer Instance = new();
        public bool Equals(ItemSignature? x, ItemSignature? y) => x?.Category == y?.Category
            && string.Equals(x?.Noun, y?.Noun, StringComparison.OrdinalIgnoreCase);
        public int GetHashCode(ItemSignature obj) => HashCode.Combine(obj.Category, StringComparer.OrdinalIgnoreCase.GetHashCode(obj.Noun));
    }
}
